# Generated by Django 3.0.7 on 2020-08-15 16:38

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=500)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Property Type',
                'verbose_name_plural': 'Property Types',
            },
        ),
        migrations.CreateModel(
            name='UserExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='img/agent/%Y/%m/%d')),
                ('job', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('sell', 'For Sell'), ('rent', 'For Rent')], max_length=5)),
                ('address', models.CharField(max_length=200)),
                ('image1', models.ImageField(upload_to='img/properties/1/%Y/%m/%d')),
                ('image2', models.ImageField(blank=True, help_text='You can leave this field empty', null=True, upload_to='img/properties/2/%Y/%m/%d')),
                ('image3', models.ImageField(blank=True, help_text='You can leave this field empty', null=True, upload_to='img/properties/3/%Y/%m/%d')),
                ('image4', models.ImageField(blank=True, help_text='You can leave this field empty', null=True, upload_to='img/properties/4/%Y/%m/%d')),
                ('image5', models.ImageField(blank=True, help_text='You can leave this field empty', null=True, upload_to='img/properties/5/%Y/%m/%d')),
                ('price', models.FloatField(max_length=11)),
                ('bed_room', models.DecimalField(decimal_places=0, max_digits=2)),
                ('baths', models.DecimalField(decimal_places=0, max_digits=2)),
                ('garage', models.DecimalField(decimal_places=0, max_digits=2)),
                ('year_build', models.CharField(max_length=10)),
                ('home_area', models.DecimalField(decimal_places=0, max_digits=4)),
                ('garage_area', models.DecimalField(decimal_places=0, max_digits=4)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('agent', models.ForeignKey(help_text='Please select your name from list', on_delete=django.db.models.deletion.CASCADE, to='app.UserExtra')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.City')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PropertyType')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(default='some', max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='img/blog/%Y/%m/%d')),
                ('tag', models.TextField(help_text='Separate tags with two dashes from each other')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('writer', models.ForeignKey(help_text='Select your name from the list', on_delete=django.db.models.deletion.CASCADE, to='app.UserExtra')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
        migrations.CreateModel(
            name='AgentContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserExtra')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Property')),
            ],
            options={
                'verbose_name': 'Agent Contact',
                'verbose_name_plural': 'Agent Contacts',
            },
        ),
    ]
